# Generated by Django 4.2.30 on 2026-04-22 07:39

import core.fields
import core.models.base_mutation
import core.utils
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_exportablequerymodel_create_date_and_more'),
        ('grievance_social_protection', '0021_grievancechannel_historicalgrievancechannel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.UUIDField(blank=True, db_column='LegacyID', null=True)),
                ('filename', models.TextField(blank=True, max_length=1000, null=True)),
                ('mime_type', models.TextField(blank=True, max_length=255, null=True)),
                ('url', models.TextField(blank=True, max_length=1000, null=True)),
                ('document', models.TextField(blank=True, null=True)),
                ('ticket', models.ForeignKey(blank=True, db_column='TicketId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='attachment', to='grievance_social_protection.ticket')),
            ],
            options={
                'db_table': 'tblTicketAttachment',
                'managed': True,
            },
            bases=(core.utils.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AttachmentMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attachment', to='core.mutationlog')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='grievance_social_protection.ticketattachment')),
            ],
            options={
                'db_table': 'ticket_AttachmentMutation',
                'managed': True,
            },
            bases=(models.Model, core.models.base_mutation.ObjectMutation),
        ),
    ]
